#!/usr/bin/env perl

use warnings;
use strict;
use Daemon::Control;

use ENV::Util -load_dotenv;

use Cwd qw(abs_path);
use File::Basename;

my $abs_path = abs_path($0);
my $abs_dir  = dirname($0);

my @program_args;
if ($ENV{FEEDS_WORKER_COUNT}) {
  push @program_args, '--workers', $ENV{FEEDS_WORKER_COUNT};
}
if ($ENV{FEEDS_APP_PORT}) {
  push @program_args, '-l', ":$ENV{FEEDS_APP_PORT}";
}
if ($ENV{FEEDS_APP_PRELOAD}) {
  push @program_args, '--preload-app';
}
push @program_args, "$abs_dir/Feeds/bin/app.psgi";

Daemon::Control->new({
  name      => ucfirst lc $ENV{FEEDS_APP_NAME},
  lsb_start => '$syslog $remote_fs',
  lsb_stop  => '$syslog',
  lsb_sdesc => 'Feeds Proxy',
  lsb_desc  => 'Feeds Proxy',
  path      => $abs_path,

  program      => '/usr/bin/starman',
  program_args => \@program_args,

  user  => $ENV{FEEDS_OWNER},
  group => $ENV{FEEDS_GROUP},

  pid_file    => "/var/run/$ENV{FEEDS_APP_NAME}.pid",
  stderr_file => "$ENV{FEEDS_LOG_DIR}/error.log",
  stdout_file => "$ENV{FEEDS_LOG_DIR}/output.log",

  fork => 2,
})->run;
