name: Build container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: europe-west2

    outputs:
      image_ref: ${{ steps.out.outputs.image_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & push image (bin/build_container)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          bin/build_container

      - id: out
        name: Export image_ref
        run: |
          echo "image_ref=$(cat image_ref.txt)" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      image_ref: ${{ needs.build.outputs.image_ref }}
    secrets: inherit

