name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region europe-west2
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Debug auth & config
        run: |
          set -e
          echo "Active account:"
          gcloud auth list --filter=status:ACTIVE --format='value(account)'

          ACCT="$(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
          echo "Auth describe:"
          gcloud auth describe "$ACCT" --format='yaml' | sed -e 's/AccessToken:.*/AccessToken: REDACTED/'

          echo "Project:"
          gcloud config get-value project

          echo "Run region (if set):"
          gcloud config get-value run/region || true

          echo "Compute region (fallback, if set):"
          gcloud config get-value compute/region || true

          echo "Project number:"
          gcloud projects describe "$(gcloud config get-value project)" --format='value(projectNumber)'

      - name: Build & submit image
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          gcloud builds submit \
            --tag "europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/containers/feeds:${COMMIT}"
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ steps.auth.outputs.credentials_file_path }}

        run: |
          COMMIT=$(git rev-parse --short HEAD)
          gcloud run deploy feeds \
            --image "europe-west2-docker.pkg.dev/${PROJECT_ID}/containers/feeds:${COMMIT}" \
            --allow-unauthenticated \
            --memory 256Mi \
            --cpu 1 \
            --concurrency 80

