name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region europe-west2
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & submit image
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          gcloud builds submit --tag "europe-west2-docker.pkg.dev/${PROJECT_ID}/containers/feeds:${COMMIT}"
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          gcloud run deploy feeds \
            --image "europe-west2-docker.pkg.dev/${PROJECT_ID}/containers/feeds:${COMMIT}" \
            --allow-unauthenticated \
            --memory 256Mi \
            --cpu 1 \
            --concurrency 80

